# Generated by Django 2.2.1 on 2019-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotitle', models.CharField(max_length=200)),
                ('cocontents', models.TextField()),
                ('user_name', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.FileField(null=True, upload_to='')),
                ('family', models.CharField(choices=[('과일', '과일'), ('야채', '야채'), ('유제품', '유제품'), ('육류', '육류'), ('어류', '어류'), ('기타', '기타')], default='과일', max_length=200)),
                ('date', models.CharField(choices=[('1', '1일'), ('2', '2일'), ('3', '3일'), ('4', '4일'), ('5', '5일'), ('6', '6일'), ('7', '7일'), ('8', '8일'), ('9', '9일'), ('10', '10일'), ('11', '11일'), ('12', '12일'), ('13', '13일'), ('14', '14일'), ('15', '15일'), ('16', '16일'), ('17', '17일'), ('18', '18일'), ('19', '19일'), ('20', '20일'), ('21', '21일'), ('22', '22일'), ('23', '23일'), ('24', '24일'), ('25', '25일'), ('26', '26일'), ('27', '27일'), ('28', '28일'), ('29', '29일'), ('30', '30일'), ('31', '31일')], default='1', max_length=200)),
                ('month', models.CharField(choices=[('1', '1월'), ('2', '2월'), ('3', '3월'), ('4', '4월'), ('5', '5월'), ('6', '6월'), ('7', '7월'), ('8', '8월'), ('9', '9월'), ('10', '10월'), ('11', '11월'), ('12', '12월')], default='5', max_length=200)),
                ('year', models.CharField(choices=[('2019', '2019년'), ('2020', '2020년'), ('2021', '2021년'), ('2022', '2022년'), ('2023', '2023년')], default='2019', max_length=200)),
                ('memo', models.TextField(max_length=200)),
            ],
        ),
    ]
