# Generated by Django 2.2.1 on 2019-05-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copost',
            old_name='cocontents',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='copost',
            old_name='cotitle',
            new_name='title',
        ),
    ]
